Spice__2/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice__2.Data;
using Spice__2.Models;
using Spice__2.Utility;

namespace Spice__2.Areas.Admin.Controllers
{   
    [Authorize(Roles = SD.ManegerUser)]
    [Area("Admin")]
    public class CategoryController : Controller
    {

        private readonly ApplicationDbContext _db; //  This is our local object.

        public CategoryController(ApplicationDbContext db) // This is a constructor used for dependency injection. This is retrieved from our Container.
        {
            _db = db;
        }

        //Get----> retreive everyting from database and pass it into the view.
        public async Task<IActionResult> Index()
        {
            return View(await _db.Category.ToListAsync());
        }
        //-------------------------------------------------------------------------//
        //Get ---> Create
        public IActionResult Create()
        {
            return View();
        }
        //----------------------------asp-action-----------------------------------//
        //POST --- Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)  // validation happens on Server side to check that users do not leave the empty space in the input place.
            {
                // if is valid
                _db.Category.Add(category);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
        //-----------------------------------------------------------------------//
        //Get -- Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _db.Category.FindAsync(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        //--------------------------------------------------------------------------//
        //POST ---> Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            // if it is valid
            if (ModelState.IsValid)
            {
                _db.Category.Update(category);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
        //--------------------------------------------------------------------//
        //Get -- Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _db.Category.FindAsync(id);

            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        //--------------------------------------------------------------------//
        //POST -- Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int? id)
        {
            var category = await _db.Category.FindAsync(id);

            if (category == null)
            {
                return View();
            }

            _db.Category.Remove(category);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        //---------------------------------------------------------------------//
        //Get -- Details
        public async Task<IActionResult> Details(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var category = await _db.Category.FindAsync(id);

            if(category == null)
            {
                return NotFound();
            }

            return View(category);
        //----------------------------------------------------------------------//    
        }
    }
}

Spice__2/Areas/Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice__2.Data;
using Spice__2.Models;
using Spice__2.Utility;

namespace Spice__2.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManegerUser)]
    [Area("Admin")]
    public class CouponController : Controller
    {

        private readonly ApplicationDbContext _db;

        public CouponController(ApplicationDbContext db) //--> Constructor
        {
            _db = db;
        }

        //Retrieve all of the coupons from database and pass them to the view-----------------//
        public async Task<IActionResult> Index()
        {
            return View(await _db.Coupon.ToListAsync());
        }
        //-----------------------------------------------------------//
        //GET -- CREATE
        public IActionResult Create()
        {
            return View();
        }
        //-----------------------------------------------------------//
        //POST -- CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Coupon coupons)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files; //--> We want to fetch the Image uploaded in the form and store it into the variable files. 
                if (files.Count > 0) //--> if the files uploaded fron front-end thne the action.
                {
                    byte[] p1 = null; 

                    using (var fs1 = files[0].OpenReadStream())  //--> We converted the Image into the byte Array. Because we want to put it into database.
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray(); //--> It converts our Image to streams of byte and put it into p1 variable.
                        }
                    }

                    coupons.Picture = p1;
                }

                _db.Coupon.Add(coupons);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(coupons);
        }
        //-----------------------------------------------------------//
        //EDIT -- GET
        public async Task<IActionResult> Edit(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }

            var coupon = await _db.Coupon.SingleOrDefaultAsync(m => m.Id == id);

            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);
        }
        //------------------------------------------------------------//
        //EDIT -- POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Coupon coupon)
        {
            if (coupon.Id == 0)
            {
                return NotFound();
            }

            var couponFromDb = await _db.Coupon.Where(c => c.Id == coupon.Id).FirstOrDefaultAsync();

            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }

                    couponFromDb.Picture = p1;
                }

                couponFromDb.MinimumAmount = coupon.MinimumAmount;
                couponFromDb.Name = coupon.Name;
                couponFromDb.Discount = coupon.Discount;
                couponFromDb.CouponType = coupon.CouponType;
                couponFromDb.IsActive = coupon.IsActive;

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(coupon);
        }


        //------------------------------------------------------------//
        //GET -- Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coupon = await _db.Coupon.FirstOrDefaultAsync();  //-->Sync with DB.

            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);

        }

        //------------------------------------------------------------//
        //GET -- DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coupon = await _db.Coupon.SingleOrDefaultAsync(m => m.Id == id);

            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);

        }
        //------------------------------------------------------------//
        //POST -- DELETE
        [HttpPost, ActionName("Delete") ]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int? id)
        {
          
            var coupon = await _db.Coupon.SingleOrDefaultAsync(m => m.Id == id);
                     
            _db.Coupon.Remove(coupon);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
       //------------------------------------------------------------//
    }
}

Spice__2/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice__2.Data;
using Spice__2.Utility;

namespace Spice__2.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManegerUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        //-----------------------------------------------//  We want to show all users inide the list except those that has logged in.
        public async Task<IActionResult> Index()
        {
            var claimIdentity = (ClaimsIdentity) this.User.Identity;  
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            
            return View(await _db.ApplicationUser.Where(u=>u.Id != claim.Value).ToListAsync()); 
        }
        //------------------------------------------------------------------------------------//
        public async Task<IActionResult> Lock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);

            applicationUser.LockoutEnd = DateTime.Now.AddYears(1000); //--> By this method user will be locked inside the database.

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        //------------------------------------------------------------------------------------//
        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);

            applicationUser.LockoutEnd = DateTime.Now; //--> By this method user will be Unlocked inside the database.

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        //------------------------------------------------------------------------------------//
    }
}

Spice__2/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Cretae" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Spice__2/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus-square"></i> &nbsp; Create New</a>
</p>

Spice__2/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int


    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-Id="@Model" value="Delete" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List </a>
    </div>
       
    

Spice__2/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int

    
    <div class="row">

        <div class="col-6">
            <a asp-action="Edit" class="btn btn-info form-control" asp-route-Id="@Model">Edit</a>
        </div>
        <div class="col-6">
            <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
        </div>
    </div>

Spice__2/Views/Shared/_EditAndBackToListButton.cshtml
@model int  

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-Id="@Model" value="Update" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List </a>
    </div>
</div>

Spice__2/Views/Shared/_Layout.cshtml
@using Spice__2.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Online Restaurant</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search_background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">

                    <img src="~/images/Mild.png" width="30" height="30" />
                    <img src="~/images/spicy.png" width="30" height="30" />
                    <img src="~/images/verySpicy.png" width="30" height="30" />

                    <label class="text-info" style="cursor:pointer">Spice Online Restaurant</label>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.IsInRole(SD.ManegerUser)) //--> By this condition we declare that if the user role is a Manager then the Content Management menu should be shown.
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Sub Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="MenuItem" asp-area="Admin">Menu Items</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">Coupons</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Admin">Users</a>
                                </div>
                            </li>
                        }

                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount) != null)
                        {
                            <li style="color:white">
                                @{
                                    var count = HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount);
                                }
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li style="color:white">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color: #343a40;">
        <div class="container">
            &copy; 2019 - My Online Restaurant - Develoed by Nima Eivazzadeh
        </div>
    </footer>

    <environment include="Development">
        <script src="https://cdn.tiny.cloud/1/l5nf5x6cridp9nqy4ww3g3p8j2cm8su6p8q3qljkf24ithy6/tinymce/5/tinymce.min.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/jquery-ui.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdn.tiny.cloud/1/l5nf5x6cridp9nqy4ww3g3p8j2cm8su6p8q3qljkf24ithy6/tinymce/5/tinymce.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="~/js/jquery-ui.js"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Spice__2/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Spice__2/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px"> 
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>

        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>

        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash"></i>
        </a>
    </div>
</td>

Spice__2/Views/Shared/_ThumbnailAreaPartial.cshtml
@model  IEnumerable<MenuItem>



@if (Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ", string.Empty) menu-restaurant">
        <div class="row">
            <h3 class="text-success"> @Model.FirstOrDefault().Category.Name </h3>
        </div>


        @foreach( var item in Model)
        { 
            <div class="border border-info rounded col-12" style="margin-bottom:10px; padding:10px;">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.Image" width="99%" style="border-radius:5px; border:1px solid #bbb9b9" />
                    </div>
                    <div class="col-md-9 col-sd-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px; color:maroon">@item.Name</label>
                                @if (item.Spicyness == "1")
                                {
                                    <img srcset="/images/Mild.png" width="42" height="42" title="Mild" />
                                }
                                @if (item.Spicyness == "2")
                                {
                                    <img srcset="/images/spicy.png" width="42" height="42" title="Spicy" />
                                }
                                @if (item.Spicyness == "3")
                                {
                                    <img srcset="/images/verySpicy.png" width="42" height="42" title="verySpicy" />
                                }
                            </div>
                            <div class="col-4 text-right" style="color:maroon">
                                <h4>$@item.Price</h4>
                            </div>
                        
                        </div>

                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(item.Description)</p> 
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">Details</a>
                        </div>

                    </div>
                </div>
            </div>
        }

        <div class="p-4">

        </div>


    </div>
}